### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by samuela** [SciML/DiffEqFlux.jl#334]
I just added DiffEqFlux to my project, but it fails to precompile:
```
(odecontrol) pkg> add DiffEqFlux
  Resolving package versions...
   Updating `~/dev/research/julia/odecontrol/Project.toml`
 [no changes]
   Updating `~/dev/research/julia/odecontrol/Manifest.toml`
 [no changes]

(odecontrol) pkg> update DiffEqFlux
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Updating `~/dev/research/julia/odecontrol/Project.toml`
 [no changes]
   Updating `~/dev/research/julia/odecontrol/Manifest.toml`
 [no changes]

julia> using DiffEqFlux
[ Info: Precompiling DiffEqFlux [aae7a2af-3d4f-5e19-a356-7da93b79d9d0]
ERROR: LoadError: LoadError: UndefVarError: trainable not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
 [2] top-level scope at /Users/skainswo/.julia/packages/DiffEqFlux/vOgUc/src/ffjord.jl:2
 [3] include(::Module, ::String) at ./Base.jl:377
 [4] include(::String) at /Users/skainswo/.julia/packages/DiffEqFlux/vOgUc/src/DiffEqFlux.jl:1
 [5] top-level scope at /Users/skainswo/.julia/packages/DiffEqFlux/vOgUc/src/DiffEqFlux.jl:68
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] top-level scope at none:2
 [8] eval at ./boot.jl:331 [inlined]
 [9] eval(::Expr) at ./client.jl:449
 [10] top-level scope at ./none:3
in expression starting at /Users/skainswo/.julia/packages/DiffEqFlux/vOgUc/src/ffjord.jl:2
in expression starting at /Users/skainswo/.julia/packages/DiffEqFlux/vOgUc/src/DiffEqFlux.jl:68
ERROR: Failed to precompile DiffEqFlux [aae7a2af-3d4f-5e19-a356-7da93b79d9d0] to /Users/skainswo/.julia/compiled/v1.4/DiffEqFlux/BdO4p_mVV4U.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1272
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
```

Here's the entry in my Manifest.toml:
```toml
[[DiffEqFlux]]
deps = ["Adapt", "BlackBoxOptim", "DiffEqBase", "DiffEqSensitivity", "DiffResults", "Distributions", "Flux", "ForwardDiff", "LinearAlgebra", "Logging", "Optim", "Printf", "ProgressLogging", "RecursiveArrayTools", "Requires", "ReverseDiff", "StaticArrays", "Tracker", "Zygote", "ZygoteRules"]
git-tree-sha1 = "ffd907c3ab14dc6bfc17f10c8ae3fb08d339c6b5"
uuid = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
version = "1.16.0"
```
